#                                        #
#               IrisTicket               #
#                                        #

database:
  useMYSQL: false     # Type false to use local database (database.db) or Type true to use MYSQL database
  MYSQL:              # I recommend using mysql in BungeeCord MultiServer
    url: 'jdbc:mysql://...'
    port: 3306
    username: 'root'
    password: 'passwd'
    database: 'IrisTicket'

categories:
  - 'General color:6'   # Insert into color:<number> tag
  - 'Report color:c'    # the color of the category
  - 'Help color:3'

permissions:
  admin:
    ticket-all-list: IrisTicket.admin
    ticket-all-view: IrisTicket.admin
    ticket-all-comment: IrisTicket.admin
    ticket-all-close: IrisTicket.admin
  user:
    ticket-create: null       # Type 'null' if the user does not need to have
    ticket-his-view: null     # permissions to use the function
    ticket-his-list: null
    ticket-his-comment: null
    ticket-his-close: null
  max-opened-tickets: 1

telegram:
  useTelegram: false
  token: '2049667294:AAG6qudp4rsuAuDNZ0p4H624AIqY2hwdX4o'

language:
  list:
    noticket: '&4No tickets found!'
    header:
      - '&8--------------------------------'
      - '&2You are in the %page_actual% of %page_total% page'
      - ''
    footer:
      - ''
      - '&7Actions &8» %arrows%'
      - '&8--------------------------------'
    commentsamount: '&8(%commentamount% comments)'
  ticket:
    header:
      - '&8---------- &7Ticket %id% &8----------'
      - '&8• &aStatus &7» %status%'
      - '&8• &7Author &7» &7%author%'
      - '&8• &aCategory &7» %category%'
      - '&8• &aDate &7» %date%'
      - ''
      - '&7Related comments'
    comments: '&8| &7%author%&f: %text%'
    footer:
      - '&7Actions &8» %comment% %close%'
      - '&8--------------------------------'
    buttons:
      comment: '&7[Comment]'
      close: '&c[Close]'
      open: '&a[Open]'
    status:
      opened: '&aOpened'
      closed: '&cClosed'

  selectcategory:
    - ''
    - '&8---------- &7Ticket &8----------'
    - '&7Please, select the category!'
    - ''
    - '%categories%'
    - '&8--------------------------------'

  help:
    - '&7Ticket help'
    - '/tk <args>'

  general:
    createticket: '&aTicket %id% &acreated successfully!'
    closeticket: '&aTicket %id% &aclosed successfully!'
    openticket: '&aTicket %id% &aopened successfully!'
    addcomment: '&aComment added successfully!'
    tootickets: '&cYou have too many open tickets!'
    nopermissions: '&cInsufficient permissions!'

  arrows:
    right: '->'
    left: '<-'

#configuration plugin
#by Madacaos with heart <3